# Generated by Django 5.1.1 on 2024-10-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_new_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_change_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
