# Generated by Django 5.1.7 on 2025-10-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_emailverification_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_change_token',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Токен смены email'),
        ),
    ]
