# Generated by Django 5.1.7 on 2025-07-24 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_name', models.CharField(blank=True, max_length=50, verbose_name='Персонаж')),
                ('skin_name', models.CharField(blank=True, max_length=50, verbose_name='Образ')),
                ('price_char', models.IntegerField(blank=True, null=True, verbose_name='Цена персонажа')),
                ('price_skin', models.IntegerField(blank=True, null=True, verbose_name='Цена образа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('server', models.CharField(choices=[('nordic', 'EU Nordic & East'), ('west', 'EU West'), ('japan', 'Japan'), ('north', 'Latin America North'), ('south', 'Latin America South'), ('namerica', 'North America'), ('russia', 'Russia'), ('turkey', 'Turkey'), ('other', 'Другой сервер')], default='west', max_length=20, verbose_name='Сервер')),
                ('account_name', models.CharField(default='default_name', max_length=50, verbose_name='Никнейм аккаунта')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skins_orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Скины и персонажи',
                'verbose_name_plural': 'Скины и персонажи',
            },
        ),
    ]
