services:
  postgres:
    ports: []

  redis:
    ports: []

  web:
    volumes: []
    env_file:
      - .env
    restart: always

  celery-worker:
    volumes: []
    env_file:
      - .env
    restart: always

  celery-beat:
    volumes: []
    env_file:
      - .env
    restart: always

  celery-flower:
    env_file:
      - .env
    restart: always
  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: always
