# Generated by Django 5.1.7 on 2025-09-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallet_held_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Пополнение'), ('withdraw', 'Вывод'), ('sale', 'Продажа'), ('purchase', 'Покупка'), ('refund', 'Возврат'), ('hold', 'Заморозка')], max_length=10),
        ),
    ]
