name: CI

on: workflow_dispatch
jobs:
    print:
        runs-on: ubuntu-latest
        steps:
          - name: Print to console!
            run: echo Hello GH Actions!



# on:
#   push:
#     branches: [ main ]
#   pull_request:

# jobs:
#   docker-build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Забрать код из репозитория
#         uses: actions/checkout@v4

#       - name: Собрать Docker image
#         run: docker build -t myapp .
