# Generated by Django 5.1.1 on 2024-12-09 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_rpservice_seller_alter_rpservice_server_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(blank=True, max_length=100, null=True)),
                ('all', models.BooleanField(default=False)),
                ('gifts_for_rp', models.BooleanField(default=False)),
                ('prepaid_cards', models.BooleanField(default=False)),
                ('rp_account', models.BooleanField(default=False)),
                ('sell', models.BooleanField(default=False)),
                ('rent', models.BooleanField(default=False)),
                ('chests', models.BooleanField(default=False)),
                ('chests_with_keys', models.BooleanField(default=False)),
                ('skins', models.BooleanField(default=False)),
                ('spheres', models.BooleanField(default=False)),
                ('other', models.BooleanField(default=False)),
                ('service_type', models.CharField(blank=True, max_length=100, null=True)),
                ('price_range', models.CharField(blank=True, max_length=100, null=True)),
                ('service_position', models.CharField(blank=True, max_length=100, null=True)),
                ('rp_1650', models.BooleanField(default=False)),
                ('rp_2650', models.BooleanField(default=False)),
                ('rp_3650', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='products.category')),
            ],
        ),
    ]
