# Generated by Django 5.1.1 on 2024-12-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_accountservice_server_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountservice',
            name='category',
        ),
        migrations.RemoveField(
            model_name='battlepassservice',
            name='category',
        ),
        migrations.RemoveField(
            model_name='boostservice',
            name='category',
        ),
        migrations.RemoveField(
            model_name='donationservice',
            name='category',
        ),
        migrations.RemoveField(
            model_name='generalservice',
            name='category',
        ),
        migrations.RemoveField(
            model_name='otherservice',
            name='category',
        ),
        migrations.RemoveField(
            model_name='qualificationservice',
            name='category',
        ),
        migrations.RemoveField(
            model_name='rpservice',
            name='category',
        ),
        migrations.RemoveField(
            model_name='trainingservice',
            name='category',
        ),
        migrations.AddField(
            model_name='accountservice',
            name='filter_type',
            field=models.CharField(default='all', help_text='Выберите, к какому фильтру относится эта запись', max_length=50, verbose_name='Тип фильтра'),
        ),
        migrations.AddField(
            model_name='battlepassservice',
            name='filter_type',
            field=models.CharField(default='all', help_text='Выберите, к какому фильтру относится эта запись', max_length=50, verbose_name='Тип фильтра'),
        ),
        migrations.AddField(
            model_name='boostservice',
            name='filter_type',
            field=models.CharField(default='all', help_text='Выберите, к какому фильтру относится эта запись', max_length=50, verbose_name='Тип фильтра'),
        ),
        migrations.AddField(
            model_name='donationservice',
            name='filter_type',
            field=models.CharField(default='all', help_text='Выберите, к какому фильтру относится эта запись', max_length=50, verbose_name='Тип фильтра'),
        ),
        migrations.AddField(
            model_name='generalservice',
            name='filter_type',
            field=models.CharField(default='all', help_text='Выберите, к какому фильтру относится эта запись', max_length=50, verbose_name='Тип фильтра'),
        ),
        migrations.AddField(
            model_name='otherservice',
            name='filter_type',
            field=models.CharField(default='all', help_text='Выберите, к какому фильтру относится эта запись', max_length=50, verbose_name='Тип фильтра'),
        ),
        migrations.AddField(
            model_name='qualificationservice',
            name='filter_type',
            field=models.CharField(default='all', help_text='Выберите, к какому фильтру относится эта запись', max_length=50, verbose_name='Тип фильтра'),
        ),
        migrations.AddField(
            model_name='rpservice',
            name='filter_type',
            field=models.CharField(default='all', help_text='Выберите, к какому фильтру относится эта запись', max_length=50, verbose_name='Тип фильтра'),
        ),
        migrations.AddField(
            model_name='trainingservice',
            name='filter_type',
            field=models.CharField(default='all', help_text='Выберите, к какому фильтру относится эта запись', max_length=50, verbose_name='Тип фильтра'),
        ),
    ]
