# Generated by Django 5.1.1 on 2024-12-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_accountservice_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountservice',
            name='filter_type',
        ),
        migrations.RemoveField(
            model_name='battlepassservice',
            name='filter_type',
        ),
        migrations.RemoveField(
            model_name='boostservice',
            name='filter_type',
        ),
        migrations.RemoveField(
            model_name='donationservice',
            name='filter_type',
        ),
        migrations.RemoveField(
            model_name='generalservice',
            name='filter_type',
        ),
        migrations.RemoveField(
            model_name='otherservice',
            name='filter_type',
        ),
        migrations.RemoveField(
            model_name='qualificationservice',
            name='filter_type',
        ),
        migrations.RemoveField(
            model_name='trainingservice',
            name='filter_type',
        ),
        migrations.AlterField(
            model_name='rpservice',
            name='filter_type',
            field=models.CharField(choices=[('all', 'Все'), ('gifts_for_rp', 'Подарки за RP'), ('prepaid_cards', 'Карты предоплаты'), ('rp_account', 'RP с заходом на аккаунт')], help_text='Выберите, к какому фильтру относится эта запись', max_length=50, verbose_name='Тип фильтра'),
        ),
    ]
