# Generated by Django 5.1.1 on 2024-12-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_accountservice_filter_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationservice',
            name='filter_type',
            field=models.CharField(choices=[('chests', 'Сундуки'), ('chests_with_keys', 'Сундуки+ключи'), ('skins', 'Скины'), ('spheres', 'Сферы'), ('other', 'Прочее')], default='default_value', help_text='Выберите, к какому фильтру относится эта запись', max_length=50, verbose_name='Тип фильтра'),
        ),
        migrations.AlterField(
            model_name='rpservice',
            name='filter_type',
            field=models.CharField(choices=[('gifts_for_rp', 'Подарки за RP'), ('prepaid_cards', 'Карты предоплаты'), ('rp_account', 'RP с заходом на аккаунт')], help_text='Выберите, к какому фильтру относится эта запись', max_length=50, verbose_name='Тип фильтра'),
        ),
    ]
