# Generated by Django 5.1.1 on 2024-12-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_donationservice_filter_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlepassservice',
            name='filter_type',
            field=models.CharField(choices=[('1650 RP', '1650 RP'), ('2650 RP', '2650 RP'), ('3650 RP', '3650 RP')], default='default_value', help_text='Выберите, к какому фильтру относится эта запись', max_length=50, verbose_name='Тип фильтра'),
        ),
        migrations.AddField(
            model_name='boostservice',
            name='filter_type',
            field=models.CharField(choices=[('solo', 'Соло буст'), ('duo', 'Дуо буст')], default='default_value', help_text='Выберите, к какому фильтру относится эта запись', max_length=50, verbose_name='Тип фильтра'),
        ),
        migrations.AddField(
            model_name='generalservice',
            name='filter_type',
            field=models.CharField(choices=[('battle_pass_boost', 'Прокачка боевого пропуска'), ('champion_mastery_boost', 'Прокачка мастерства чемпиона'), ('aram', 'ARAM'), ('clash', 'Clash'), ('normal_game', 'Обычная игра'), ('cooperative_game', 'Совместная игра'), ('leaverbuster_recovery', 'Отыгрыш ливбустера'), ('chat_ban_recovery', 'Отыгрыш банчата'), ('account_leveling', 'Прокачка уровня аккаунта'), ('mastery_token_farm', 'Фарм жетонов мастерства'), ('deboost', 'Дебуст')], default='default_value', help_text='Выберите, к какому фильтру относится эта запись', max_length=50, verbose_name='Тип фильтра'),
        ),
        migrations.AddField(
            model_name='otherservice',
            name='filter_type',
            field=models.CharField(choices=[('guides', 'Гайды'), ('other', 'Прочее')], default='default_value', help_text='Выберите, к какому фильтру относится эта запись', max_length=50, verbose_name='Тип фильтра'),
        ),
        migrations.AddField(
            model_name='trainingservice',
            name='filter_type',
            field=models.CharField(choices=[('top', 'Топ'), ('jungle', 'Лес'), ('mid', 'Мид'), ('adc', 'АДК'), ('support', 'Сап'), ('any role', 'Любая роль')], default='default_value', help_text='Выберите, к какому фильтру относится эта запись', max_length=50, verbose_name='Тип фильтра'),
        ),
    ]
