# Generated by Django 5.1.1 on 2024-12-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_battlepassservice_filter_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountservice',
            name='account_level',
            field=models.PositiveIntegerField(default=1, verbose_name='Уровень аккаунта'),
        ),
        migrations.AddField(
            model_name='accountservice',
            name='auto_delivery',
            field=models.BooleanField(default=False, verbose_name='Автоматическая выдача'),
        ),
        migrations.AddField(
            model_name='accountservice',
            name='character_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество персонажей'),
        ),
        migrations.AddField(
            model_name='accountservice',
            name='filter_type',
            field=models.CharField(choices=[('sell', 'Продажа'), ('rent', 'Аренда')], default='default_value', help_text='Выберите, к какому фильтру относится эта запись', max_length=50, verbose_name='Тип фильтра'),
        ),
        migrations.AddField(
            model_name='accountservice',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Пометить, если предложение активно', verbose_name='Активное'),
        ),
        migrations.AddField(
            model_name='accountservice',
            name='message',
            field=models.TextField(blank=True, verbose_name='Сообщение покупателю после оплаты'),
        ),
        migrations.AddField(
            model_name='accountservice',
            name='skin_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество скинов'),
        ),
        migrations.AddField(
            model_name='battlepassservice',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Пометить, если предложение активно', verbose_name='Активное'),
        ),
        migrations.AddField(
            model_name='battlepassservice',
            name='message',
            field=models.TextField(blank=True, verbose_name='Сообщение покупателю после оплаты'),
        ),
        migrations.AddField(
            model_name='boostservice',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Пометить, если предложение активно', verbose_name='Активное'),
        ),
        migrations.AddField(
            model_name='boostservice',
            name='message',
            field=models.TextField(blank=True, verbose_name='Сообщение покупателю после оплаты'),
        ),
        migrations.AddField(
            model_name='donationservice',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Пометить, если предложение активно', verbose_name='Активное'),
        ),
        migrations.AddField(
            model_name='donationservice',
            name='message',
            field=models.TextField(blank=True, verbose_name='Сообщение покупателю после оплаты'),
        ),
        migrations.AddField(
            model_name='generalservice',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Пометить, если предложение активно', verbose_name='Активное'),
        ),
        migrations.AddField(
            model_name='generalservice',
            name='message',
            field=models.TextField(blank=True, verbose_name='Сообщение покупателю после оплаты'),
        ),
        migrations.AddField(
            model_name='otherservice',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Пометить, если предложение активно', verbose_name='Активное'),
        ),
        migrations.AddField(
            model_name='otherservice',
            name='message',
            field=models.TextField(blank=True, verbose_name='Сообщение покупателю после оплаты'),
        ),
        migrations.AddField(
            model_name='qualificationservice',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Пометить, если предложение активно', verbose_name='Активное'),
        ),
        migrations.AddField(
            model_name='qualificationservice',
            name='message',
            field=models.TextField(blank=True, verbose_name='Сообщение покупателю после оплаты'),
        ),
        migrations.AddField(
            model_name='rpservice',
            name='auto_delivery',
            field=models.BooleanField(default=False, verbose_name='Автоматическая выдача'),
        ),
        migrations.AddField(
            model_name='rpservice',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Пометить, если предложение активно', verbose_name='Активное'),
        ),
        migrations.AddField(
            model_name='rpservice',
            name='message',
            field=models.TextField(blank=True, verbose_name='Сообщение покупателю после оплаты'),
        ),
        migrations.AddField(
            model_name='trainingservice',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Пометить, если предложение активно', verbose_name='Активное'),
        ),
        migrations.AddField(
            model_name='trainingservice',
            name='message',
            field=models.TextField(blank=True, verbose_name='Сообщение покупателю после оплаты'),
        ),
        migrations.AlterField(
            model_name='accountservice',
            name='description',
            field=models.TextField(blank=True, verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='accountservice',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='battlepassservice',
            name='description',
            field=models.TextField(blank=True, verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='battlepassservice',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='boostservice',
            name='description',
            field=models.TextField(blank=True, verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='boostservice',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='donationservice',
            name='description',
            field=models.TextField(blank=True, verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='donationservice',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='generalservice',
            name='description',
            field=models.TextField(blank=True, verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='generalservice',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='otherservice',
            name='description',
            field=models.TextField(blank=True, verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='otherservice',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='qualificationservice',
            name='description',
            field=models.TextField(blank=True, verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='qualificationservice',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='rpservice',
            name='description',
            field=models.TextField(blank=True, verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='rpservice',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='trainingservice',
            name='description',
            field=models.TextField(blank=True, verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='trainingservice',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Краткое описание'),
        ),
    ]
