# Generated by Django 5.1.1 on 2024-12-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_accountservice_account_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountservice',
            name='rank',
            field=models.CharField(choices=[('IRON', 'Железо'), ('BRONZE', 'Бронза'), ('SILVER', 'Серебро'), ('GOLD', 'Золото'), ('PLATINUM', 'Платина'), ('EMERALD', 'Изумруд'), ('DIAMOND', 'Алмаз'), ('MASTER', 'Мастер'), ('GRANDMASTER', 'Гранмастер'), ('CHALLENGER', 'Претендент'), ('NO_RANK', 'Нет ранга')], default='NO_RANK', max_length=20, verbose_name='Ранг аккаунта'),
        ),
    ]
