# Generated by Django 5.1.1 on 2024-12-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_accountservice_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationservice',
            name='receiving_method',
            field=models.CharField(choices=[('GIFT', 'Подарком'), ('LOGIN', 'С заходом на аккаунт')], default='GIFT', max_length=10, verbose_name='Способ получения'),
        ),
    ]
