# Generated by Django 5.1.1 on 2024-12-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_donationservice_receiving_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='boostservice',
            name='rank_range',
            field=models.CharField(choices=[('IRON_BRONZE', 'Железо 4 - Бронза 4'), ('BRONZE_SILVER', 'Бронза 4 - Серебро 4'), ('SILVER_GOLD', 'Серебро 4 - Золото 4'), ('GOLD_PLATINUM', 'Золото 4 - Платина 4'), ('PLATINUM_EMERALD', 'Платина 4 - Изумруд 4'), ('EMERALD_DIAMOND', 'Изумруд 4 - Алмаз 4'), ('DIAMOND_MASTER', 'Алмаз 4 - Мастер'), ('MASTER_GRANDMASTER', 'Мастер - Грандмастер'), ('GRANDMASTER_PRETENDER', 'Грандмастер - Претендент')], default='IRON_BRONZE', max_length=21, verbose_name='Диапазон'),
        ),
    ]
