# Generated by Django 5.1.1 on 2024-12-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_boostservice_rank_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherservice',
            name='auto_delivery',
            field=models.BooleanField(default=False, verbose_name='Автоматическая выдача'),
        ),
        migrations.AlterField(
            model_name='trainingservice',
            name='filter_type',
            field=models.CharField(choices=[('top', 'Топ'), ('jungle', 'Лес'), ('mid', 'Мид'), ('adc', 'АДК'), ('support', 'Сап'), ('any role', 'Любая роль')], default='default_value', help_text='Выберите, к какому фильтру относится эта запись', max_length=50, verbose_name='Позиция'),
        ),
    ]
