# Generated by Django 5.1.1 on 2024-12-16 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_otherservice_auto_delivery_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filter',
        ),
    ]
