# Generated by Django 5.1.1 on 2024-12-25 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_delete_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountservice',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='account_services', to='products.category'),
        ),
    ]
