# Generated by Django 5.1.1 on 2024-12-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_accountservice_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlepassservice',
            name='filter_type',
            field=models.CharField(choices=[('ALL', 'Все'), ('1650 RP', '1650 RP'), ('2650 RP', '2650 RP'), ('3650 RP', '3650 RP')], default='default_value', help_text='Выберите, к какому фильтру относится эта запись', max_length=50, verbose_name='Тип фильтра'),
        ),
    ]
