# Generated by Django 5.1.1 on 2024-12-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_battlepassservice_filter_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountservice',
            name='filter_type',
            field=models.CharField(choices=[('ALL', 'Все'), ('sell', 'Продажа'), ('rent', 'Аренда')], default='default_value', help_text='Выберите, к какому фильтру относится эта запись', max_length=50, verbose_name='Тип фильтра'),
        ),
        migrations.AlterField(
            model_name='rpservice',
            name='filter_type',
            field=models.CharField(choices=[('ALL', 'Все'), ('gifts_for_rp', 'Подарки за RP'), ('prepaid_cards', 'Карты предоплаты'), ('rp_account', 'RP с заходом на аккаунт')], help_text='Выберите, к какому фильтру относится эта запись', max_length=50, verbose_name='Тип фильтра'),
        ),
    ]
