# Generated by Django 5.1.1 on 2024-12-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_accountservice_filter_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountservice',
            name='search_description',
            field=models.TextField(blank=True, help_text='Введите текст, который будет использован для поиска', verbose_name='Описание для поиска'),
        ),
        migrations.AddField(
            model_name='battlepassservice',
            name='search_description',
            field=models.TextField(blank=True, help_text='Введите текст, который будет использован для поиска', verbose_name='Описание для поиска'),
        ),
        migrations.AddField(
            model_name='boostservice',
            name='search_description',
            field=models.TextField(blank=True, help_text='Введите текст, который будет использован для поиска', verbose_name='Описание для поиска'),
        ),
        migrations.AddField(
            model_name='donationservice',
            name='search_description',
            field=models.TextField(blank=True, help_text='Введите текст, который будет использован для поиска', verbose_name='Описание для поиска'),
        ),
        migrations.AddField(
            model_name='generalservice',
            name='search_description',
            field=models.TextField(blank=True, help_text='Введите текст, который будет использован для поиска', verbose_name='Описание для поиска'),
        ),
        migrations.AddField(
            model_name='otherservice',
            name='search_description',
            field=models.TextField(blank=True, help_text='Введите текст, который будет использован для поиска', verbose_name='Описание для поиска'),
        ),
        migrations.AddField(
            model_name='qualificationservice',
            name='search_description',
            field=models.TextField(blank=True, help_text='Введите текст, который будет использован для поиска', verbose_name='Описание для поиска'),
        ),
        migrations.AddField(
            model_name='rpservice',
            name='search_description',
            field=models.TextField(blank=True, help_text='Введите текст, который будет использован для поиска', verbose_name='Описание для поиска'),
        ),
        migrations.AddField(
            model_name='trainingservice',
            name='search_description',
            field=models.TextField(blank=True, help_text='Введите текст, который будет использован для поиска', verbose_name='Описание для поиска'),
        ),
    ]
