# Generated by Django 5.1.1 on 2024-12-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_accountservice_search_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountservice',
            name='is_auto_delivery',
            field=models.BooleanField(default=False, help_text='Пометить, если услуга поддерживает автоматическую доставку', verbose_name='Автоматическая доставка'),
        ),
        migrations.AddField(
            model_name='accountservice',
            name='seller_is_online',
            field=models.BooleanField(default=False, help_text='Пометить, если продавец находится в сети', verbose_name='Продавец онлайн'),
        ),
        migrations.AddField(
            model_name='battlepassservice',
            name='is_auto_delivery',
            field=models.BooleanField(default=False, help_text='Пометить, если услуга поддерживает автоматическую доставку', verbose_name='Автоматическая доставка'),
        ),
        migrations.AddField(
            model_name='battlepassservice',
            name='seller_is_online',
            field=models.BooleanField(default=False, help_text='Пометить, если продавец находится в сети', verbose_name='Продавец онлайн'),
        ),
        migrations.AddField(
            model_name='boostservice',
            name='is_auto_delivery',
            field=models.BooleanField(default=False, help_text='Пометить, если услуга поддерживает автоматическую доставку', verbose_name='Автоматическая доставка'),
        ),
        migrations.AddField(
            model_name='boostservice',
            name='seller_is_online',
            field=models.BooleanField(default=False, help_text='Пометить, если продавец находится в сети', verbose_name='Продавец онлайн'),
        ),
        migrations.AddField(
            model_name='donationservice',
            name='is_auto_delivery',
            field=models.BooleanField(default=False, help_text='Пометить, если услуга поддерживает автоматическую доставку', verbose_name='Автоматическая доставка'),
        ),
        migrations.AddField(
            model_name='donationservice',
            name='seller_is_online',
            field=models.BooleanField(default=False, help_text='Пометить, если продавец находится в сети', verbose_name='Продавец онлайн'),
        ),
        migrations.AddField(
            model_name='generalservice',
            name='is_auto_delivery',
            field=models.BooleanField(default=False, help_text='Пометить, если услуга поддерживает автоматическую доставку', verbose_name='Автоматическая доставка'),
        ),
        migrations.AddField(
            model_name='generalservice',
            name='seller_is_online',
            field=models.BooleanField(default=False, help_text='Пометить, если продавец находится в сети', verbose_name='Продавец онлайн'),
        ),
        migrations.AddField(
            model_name='otherservice',
            name='is_auto_delivery',
            field=models.BooleanField(default=False, help_text='Пометить, если услуга поддерживает автоматическую доставку', verbose_name='Автоматическая доставка'),
        ),
        migrations.AddField(
            model_name='otherservice',
            name='seller_is_online',
            field=models.BooleanField(default=False, help_text='Пометить, если продавец находится в сети', verbose_name='Продавец онлайн'),
        ),
        migrations.AddField(
            model_name='qualificationservice',
            name='is_auto_delivery',
            field=models.BooleanField(default=False, help_text='Пометить, если услуга поддерживает автоматическую доставку', verbose_name='Автоматическая доставка'),
        ),
        migrations.AddField(
            model_name='qualificationservice',
            name='seller_is_online',
            field=models.BooleanField(default=False, help_text='Пометить, если продавец находится в сети', verbose_name='Продавец онлайн'),
        ),
        migrations.AddField(
            model_name='rpservice',
            name='is_auto_delivery',
            field=models.BooleanField(default=False, help_text='Пометить, если услуга поддерживает автоматическую доставку', verbose_name='Автоматическая доставка'),
        ),
        migrations.AddField(
            model_name='rpservice',
            name='seller_is_online',
            field=models.BooleanField(default=False, help_text='Пометить, если продавец находится в сети', verbose_name='Продавец онлайн'),
        ),
        migrations.AddField(
            model_name='trainingservice',
            name='is_auto_delivery',
            field=models.BooleanField(default=False, help_text='Пометить, если услуга поддерживает автоматическую доставку', verbose_name='Автоматическая доставка'),
        ),
        migrations.AddField(
            model_name='trainingservice',
            name='seller_is_online',
            field=models.BooleanField(default=False, help_text='Пометить, если продавец находится в сети', verbose_name='Продавец онлайн'),
        ),
    ]
