# Generated by Django 5.1.1 on 2025-01-09 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_accountservice_is_auto_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountservice',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='account_services', to='products.category'),
        ),
    ]
