# Generated by Django 5.1.1 on 2025-01-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_accountservice_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountservice',
            name='server',
            field=models.CharField(choices=[('nordic', 'EU Nordic & East'), ('west', 'EU West'), ('japan', 'Japan'), ('north', 'Latin America North'), ('south', 'Latin America South'), ('namerica', 'North America'), ('russia', 'Russia'), ('turkey', 'Turkey'), ('other', 'Другой сервер')], help_text='Выберите сервер', max_length=50, verbose_name='Сервер'),
        ),
        migrations.AlterField(
            model_name='boostservice',
            name='server',
            field=models.CharField(choices=[('nordic', 'EU Nordic & East'), ('west', 'EU West'), ('japan', 'Japan'), ('north', 'Latin America North'), ('south', 'Latin America South'), ('namerica', 'North America'), ('russia', 'Russia'), ('turkey', 'Turkey'), ('other', 'Другой сервер')], help_text='Выберите сервер', max_length=50, verbose_name='Сервер'),
        ),
        migrations.AlterField(
            model_name='donationservice',
            name='server',
            field=models.CharField(choices=[('nordic', 'EU Nordic & East'), ('west', 'EU West'), ('japan', 'Japan'), ('north', 'Latin America North'), ('south', 'Latin America South'), ('namerica', 'North America'), ('russia', 'Russia'), ('turkey', 'Turkey'), ('other', 'Другой сервер')], help_text='Выберите сервер', max_length=50, verbose_name='Сервер'),
        ),
        migrations.AlterField(
            model_name='qualificationservice',
            name='server',
            field=models.CharField(choices=[('nordic', 'EU Nordic & East'), ('west', 'EU West'), ('japan', 'Japan'), ('north', 'Latin America North'), ('south', 'Latin America South'), ('namerica', 'North America'), ('russia', 'Russia'), ('turkey', 'Turkey'), ('other', 'Другой сервер')], help_text='Выберите сервер', max_length=50, verbose_name='Сервер'),
        ),
        migrations.AlterField(
            model_name='rpservice',
            name='server',
            field=models.CharField(choices=[('nordic', 'EU Nordic & East'), ('west', 'EU West'), ('japan', 'Japan'), ('north', 'Latin America North'), ('south', 'Latin America South'), ('namerica', 'North America'), ('russia', 'Russia'), ('turkey', 'Turkey'), ('other', 'Другой сервер')], help_text='Выберите сервер', max_length=50, verbose_name='Сервер'),
        ),
    ]
