# Generated by Django 5.1.1 on 2025-02-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_accountservice_server_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountservice',
            name='filter_type',
            field=models.CharField(choices=[('sell', 'Продажа'), ('rent', 'Аренда')], default='sell', help_text='Выберите, к какому фильтру относится эта запись', max_length=50, verbose_name='Тип фильтра'),
        ),
    ]
