# Generated by Django 5.1.1 on 2025-02-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_accountservice_server_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlepassservice',
            name='filter_type',
            field=models.CharField(choices=[('1650 RP', '1650 RP'), ('2650 RP', '2650 RP'), ('3650 RP', '3650 RP')], default='default_value', help_text='Выберите, к какому фильтру относится эта запись', max_length=50, verbose_name='Тип фильтра'),
        ),
        migrations.AlterField(
            model_name='donationservice',
            name='filter_type',
            field=models.CharField(choices=[('chests', 'Сундуки'), ('chests_with_keys', 'Сундуки+ключи'), ('skins', 'Скины'), ('spheres', 'Сферы'), ('other', 'Прочее')], default='chests', help_text='Выберите, к какому фильтру относится эта запись', max_length=50, verbose_name='Тип фильтра'),
        ),
        migrations.AlterField(
            model_name='rpservice',
            name='filter_type',
            field=models.CharField(choices=[('gifts_for_rp', 'Подарки за RP'), ('prepaid_cards', 'Карты предоплаты'), ('rp_account', 'RP с заходом на аккаунт')], default='gifts_for_rp', help_text='Выберите, к какому фильтру относится эта запись', max_length=50, verbose_name='Тип фильтра'),
        ),
    ]
