# Generated by Django 5.1.1 on 2025-02-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_battlepassservice_filter_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlepassservice',
            name='server',
            field=models.CharField(choices=[('nordic', 'EU Nordic & East'), ('west', 'EU West'), ('japan', 'Japan'), ('north', 'Latin America North'), ('south', 'Latin America South'), ('namerica', 'North America'), ('russia', 'Russia'), ('turkey', 'Turkey'), ('other', 'Другой сервер')], default='other', help_text='Выберите сервер', max_length=50, verbose_name='Сервер'),
        ),
    ]
