# Generated by Django 5.1.1 on 2025-02-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_battlepassservice_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlepassservice',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='Количество валюты в наличии', verbose_name='Количество'),
            preserve_default=False,
        ),
    ]
