# Generated by Django 5.1.1 on 2025-02-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_battlepassservice_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpservice',
            name='filter_type',
            field=models.CharField(choices=[('gifts_for_rp', 'Подарки за RP'), ('prepaid_cards', 'Карты предоплаты'), ('rp_account', 'RP с заходом на аккаунт')], default='gifts_for_rp', help_text='Выберите, к какому фильтру относится эта запись', max_length=50, verbose_name='Тип'),
        ),
    ]
