# Generated by Django 5.1.7 on 2025-04-08 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_rpservice_filter_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlepassservice',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_services', to='products.category'),
        ),
        migrations.AddField(
            model_name='boostservice',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_services', to='products.category'),
        ),
        migrations.AddField(
            model_name='donationservice',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_services', to='products.category'),
        ),
        migrations.AddField(
            model_name='generalservice',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_services', to='products.category'),
        ),
        migrations.AddField(
            model_name='otherservice',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_services', to='products.category'),
        ),
        migrations.AddField(
            model_name='qualificationservice',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_services', to='products.category'),
        ),
        migrations.AddField(
            model_name='rpservice',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_services', to='products.category'),
        ),
        migrations.AddField(
            model_name='trainingservice',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_services', to='products.category'),
        ),
    ]
