# Generated by Django 5.1.7 on 2025-04-10 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_battlepassservice_category_boostservice_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlepassservice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_services', to='products.category'),
        ),
        migrations.AlterField(
            model_name='boostservice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_services', to='products.category'),
        ),
        migrations.AlterField(
            model_name='donationservice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_services', to='products.category'),
        ),
        migrations.AlterField(
            model_name='generalservice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_services', to='products.category'),
        ),
        migrations.AlterField(
            model_name='otherservice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_services', to='products.category'),
        ),
        migrations.AlterField(
            model_name='qualificationservice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_services', to='products.category'),
        ),
        migrations.AlterField(
            model_name='rpservice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_services', to='products.category'),
        ),
        migrations.AlterField(
            model_name='trainingservice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_services', to='products.category'),
        ),
    ]
