# Generated by Django 5.1.7 on 2025-04-10 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_alter_battlepassservice_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationservice',
            name='category',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='donation_services', to='products.category'),
        ),
    ]
