# Generated by Django 5.1.7 on 2025-04-10 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_alter_donationservice_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlepassservice',
            name='category',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='battlepass_services', to='products.category'),
        ),
        migrations.AlterField(
            model_name='boostservice',
            name='category',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='boost_services', to='products.category'),
        ),
        migrations.AlterField(
            model_name='generalservice',
            name='category',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='general_services', to='products.category'),
        ),
        migrations.AlterField(
            model_name='otherservice',
            name='category',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='other_services', to='products.category'),
        ),
        migrations.AlterField(
            model_name='qualificationservice',
            name='category',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='qualification_services', to='products.category'),
        ),
        migrations.AlterField(
            model_name='rpservice',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rp_services', to='products.category'),
        ),
        migrations.AlterField(
            model_name='trainingservice',
            name='category',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='training_services', to='products.category'),
        ),
    ]
