# Generated by Django 5.1.7 on 2025-04-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_alter_battlepassservice_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountservice',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Количество аккаунтов в наличии', verbose_name='Количество'),
        ),
    ]
