# Generated by Django 5.1.7 on 2025-07-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_serviceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(upload_to='service_images/', verbose_name='Загрузить изображение'),
        ),
    ]
