# Generated by Django 5.1.7 on 2025-09-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_alter_serviceimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountservice',
            name='filter_type',
            field=models.CharField(choices=[('', 'Выберите категорию'), ('sell', 'Продажа'), ('rent', 'Аренда')], default='sell', help_text='Выберите, к какому фильтру относится эта запись', max_length=50, verbose_name='Тип фильтра'),
        ),
        migrations.AlterField(
            model_name='accountservice',
            name='rank',
            field=models.CharField(choices=[('', 'Выберите ранг'), ('IRON', 'Железо'), ('BRONZE', 'Бронза'), ('SILVER', 'Серебро'), ('GOLD', 'Золото'), ('PLATINUM', 'Платина'), ('EMERALD', 'Изумруд'), ('DIAMOND', 'Алмаз'), ('MASTER', 'Мастер'), ('GRANDMASTER', 'Гранмастер'), ('CHALLENGER', 'Претендент'), ('NO_RANK', 'Нет ранга')], default='NO_RANK', max_length=20, verbose_name='Ранг аккаунта'),
        ),
        migrations.AlterField(
            model_name='accountservice',
            name='server',
            field=models.CharField(choices=[('', 'Выберите сервер'), ('nordic', 'EU Nordic & East'), ('west', 'EU West'), ('japan', 'Japan'), ('north', 'Latin America North'), ('south', 'Latin America South'), ('namerica', 'North America'), ('russia', 'Russia'), ('turkey', 'Turkey'), ('other', 'Другой сервер')], default='other', help_text='Выберите сервер', max_length=50, verbose_name='Сервер'),
        ),
        migrations.AlterField(
            model_name='battlepassservice',
            name='filter_type',
            field=models.CharField(choices=[('', 'Выберите категорию'), ('1650 RP', '1650 RP'), ('2650 RP', '2650 RP'), ('3650 RP', '3650 RP')], default='default_value', help_text='Выберите, к какому фильтру относится эта запись', max_length=50, verbose_name='Тип фильтра'),
        ),
        migrations.AlterField(
            model_name='battlepassservice',
            name='server',
            field=models.CharField(choices=[('', 'Выберите сервер'), ('nordic', 'EU Nordic & East'), ('west', 'EU West'), ('japan', 'Japan'), ('north', 'Latin America North'), ('south', 'Latin America South'), ('namerica', 'North America'), ('russia', 'Russia'), ('turkey', 'Turkey'), ('other', 'Другой сервер')], default='other', help_text='Выберите сервер', max_length=50, verbose_name='Сервер'),
        ),
        migrations.AlterField(
            model_name='boostservice',
            name='filter_type',
            field=models.CharField(choices=[('', 'Выберите категорию'), ('solo', 'Соло буст'), ('duo', 'Дуо буст')], default='default_value', help_text='Выберите, к какому фильтру относится эта запись', max_length=50, verbose_name='Тип фильтра'),
        ),
        migrations.AlterField(
            model_name='boostservice',
            name='rank_range',
            field=models.CharField(choices=[('', 'Диапазон буста'), ('IRON_BRONZE', 'Железо 4 - Бронза 4'), ('BRONZE_SILVER', 'Бронза 4 - Серебро 4'), ('SILVER_GOLD', 'Серебро 4 - Золото 4'), ('GOLD_PLATINUM', 'Золото 4 - Платина 4'), ('PLATINUM_EMERALD', 'Платина 4 - Изумруд 4'), ('EMERALD_DIAMOND', 'Изумруд 4 - Алмаз 4'), ('DIAMOND_MASTER', 'Алмаз 4 - Мастер'), ('MASTER_GRANDMASTER', 'Мастер - Грандмастер'), ('GRANDMASTER_PRETENDER', 'Грандмастер - Претендент')], default='IRON_BRONZE', max_length=21, verbose_name='Диапазон'),
        ),
        migrations.AlterField(
            model_name='boostservice',
            name='server',
            field=models.CharField(choices=[('', 'Выберите сервер'), ('nordic', 'EU Nordic & East'), ('west', 'EU West'), ('japan', 'Japan'), ('north', 'Latin America North'), ('south', 'Latin America South'), ('namerica', 'North America'), ('russia', 'Russia'), ('turkey', 'Turkey'), ('other', 'Другой сервер')], default='other', help_text='Выберите сервер', max_length=50, verbose_name='Сервер'),
        ),
        migrations.AlterField(
            model_name='donationservice',
            name='filter_type',
            field=models.CharField(choices=[('', 'Выберите категорию'), ('chests', 'Сундуки'), ('chests_with_keys', 'Сундуки+ключи'), ('skins', 'Скины'), ('spheres', 'Сферы'), ('other', 'Прочее')], default='chests', help_text='Выберите, к какому фильтру относится эта запись', max_length=50, verbose_name='Тип фильтра'),
        ),
        migrations.AlterField(
            model_name='donationservice',
            name='receiving_method',
            field=models.CharField(choices=[('', 'Способ получения'), ('GIFT', 'Подарком'), ('LOGIN', 'С заходом на аккаунт')], default='GIFT', max_length=10, verbose_name='Способ получения'),
        ),
        migrations.AlterField(
            model_name='donationservice',
            name='server',
            field=models.CharField(choices=[('', 'Выберите сервер'), ('nordic', 'EU Nordic & East'), ('west', 'EU West'), ('japan', 'Japan'), ('north', 'Latin America North'), ('south', 'Latin America South'), ('namerica', 'North America'), ('russia', 'Russia'), ('turkey', 'Turkey'), ('other', 'Другой сервер')], default='other', help_text='Выберите сервер', max_length=50, verbose_name='Сервер'),
        ),
        migrations.AlterField(
            model_name='generalservice',
            name='filter_type',
            field=models.CharField(choices=[('', 'Выберите категорию'), ('battle_pass_boost', 'Прокачка боевого пропуска'), ('champion_mastery_boost', 'Прокачка мастерства чемпиона'), ('aram', 'ARAM'), ('clash', 'Clash'), ('normal_game', 'Обычная игра'), ('cooperative_game', 'Совместная игра'), ('leaverbuster_recovery', 'Отыгрыш ливбустера'), ('chat_ban_recovery', 'Отыгрыш банчата'), ('account_leveling', 'Прокачка уровня аккаунта'), ('mastery_token_farm', 'Фарм жетонов мастерства'), ('deboost', 'Дебуст')], default='default_value', help_text='Выберите, к какому фильтру относится эта запись', max_length=50, verbose_name='Тип фильтра'),
        ),
        migrations.AlterField(
            model_name='otherservice',
            name='filter_type',
            field=models.CharField(choices=[('', 'Выберите категорию'), ('guides', 'Гайды'), ('other', 'Прочее')], default='default_value', help_text='Выберите, к какому фильтру относится эта запись', max_length=50, verbose_name='Тип фильтра'),
        ),
        migrations.AlterField(
            model_name='qualificationservice',
            name='server',
            field=models.CharField(choices=[('', 'Выберите сервер'), ('nordic', 'EU Nordic & East'), ('west', 'EU West'), ('japan', 'Japan'), ('north', 'Latin America North'), ('south', 'Latin America South'), ('namerica', 'North America'), ('russia', 'Russia'), ('turkey', 'Turkey'), ('other', 'Другой сервер')], default='other', help_text='Выберите сервер', max_length=50, verbose_name='Сервер'),
        ),
        migrations.AlterField(
            model_name='rpservice',
            name='filter_type',
            field=models.CharField(choices=[('', 'Выберите категорию'), ('gifts_for_rp', 'Подарки за RP'), ('prepaid_cards', 'Карты предоплаты'), ('rp_account', 'RP с заходом на аккаунт')], default='gifts_for_rp', help_text='Выберите, к какому фильтру относится эта запись', max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='rpservice',
            name='server',
            field=models.CharField(choices=[('', 'Выберите сервер'), ('nordic', 'EU Nordic & East'), ('west', 'EU West'), ('japan', 'Japan'), ('north', 'Latin America North'), ('south', 'Latin America South'), ('namerica', 'North America'), ('russia', 'Russia'), ('turkey', 'Turkey'), ('other', 'Другой сервер')], default='other', help_text='Выберите сервер', max_length=50, verbose_name='Сервер'),
        ),
        migrations.AlterField(
            model_name='trainingservice',
            name='filter_type',
            field=models.CharField(choices=[('', 'Выберите роль'), ('top', 'Топ'), ('jungle', 'Лес'), ('mid', 'Мид'), ('adc', 'АДК'), ('support', 'Сап'), ('any role', 'Любая роль')], default='default_value', help_text='Выберите, к какому фильтру относится эта запись', max_length=50, verbose_name='Позиция'),
        ),
    ]
